#!/bin/bash

echo "🚂 RAILWAY DEPLOYMENT COMMANDS"
echo "=============================="
echo ""
echo "Since Railway CLI is installed but not authenticated,"
echo "please run these commands in your terminal:"
echo ""
echo "1. First, login to Railway:"
echo "   $ railway login"
echo ""
echo "   This will open your browser where you're already logged in."
echo "   Click 'Authorize' to connect the CLI."
echo ""
echo "2. Once logged in, navigate to the project:"
echo "   $ cd /home/terry/Desktop/finding-sports"
echo ""
echo "3. Link to your existing project:"
echo "   $ railway link"
echo ""
echo "   Select the 'findingsports-com' project from the list."
echo ""
echo "4. Deploy the current code:"
echo "   $ railway up"
echo ""
echo "This will deploy all the changes we've made!"
echo ""
echo "Alternatively, if you want me to keep trying after you login,"
echo "run this command first:"
echo ""
echo "   $ railway login"
echo ""
echo "Then let me know and I'll use the Railway CLI to deploy."